defvars 0 ; comment on defvars
{
    var1 ds.b 1 ; comment on var1
    
    var2 ds.w 2  
    var3 ds.q 1 ; comment on var3
    ; comment on var4
}

; comment bla bla bla bla bla bla bla bla ld a
label:                          ; inline comment on label
        LD A, 0
        LD HL, $0000            ; inline comment on instruction
        INC A
        SCF
        JP label2
        DEC D
        CPL A
        RST 28

;; comment 
;; @param a contains char 
.label3
        XOR A, A
